### PR TITLE
Airdrop

### PR DESCRIPTION
**Pull request by srph**
Regenerates stridejs with the new Airdrop module from https://github.com/Stride-Labs/stride/pull/1235/files.

### Other Highlights

- Publishes version 0.10-alpha, 0.11-alpha, and 0.11
- Adds proper aminoTypes
- Documents aminoTypes
- Includes tons of great changes from https://github.com/Stride-Labs/stridejs/pull/15

-----

We probably should publish 0.10 once the Airdrop module gets merged and goes live. Afterwards, let's merge this PR.

### CODE REVIEW

**Comment by srph** [comment]
Getting this for some reason on Stride Frontend: > @stride/app:dev: Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).

**Comment by assafmo** [comment]
> Getting this for some reason on Stride Frontend: > @stride/app:dev: Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).

I'll look into it. How can I reproduce this?

**Comment by srph** [comment]
@assafmo Just back from the OOO. But I forgot hahaha. I'll try to get back to it this week though.

**Comment by srph** [comment]
Leaving some updates here as I go. v0.11.0-alpha gives me these errors:

```
@stride/app:dev:  ⨯ node:crypto
@stride/app:dev: Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
@stride/app:dev: Webpack supports "data:" and "file:" URIs by default.
@stride/app:dev: You may need an additional plugin to handle "node:" URIs.
@stride/app:dev: Import trace for requested module:
@stride/app:dev: node:crypto
@stride/app:dev: ../../node_modules/.pnpm/stridejs@0.11.0-alpha/node_modules/stridejs/dist/index.js
@stride/app:dev: ./src/wallet-utils/registry.ts
@stride/app:dev: ./src/wallet-utils/index.ts
@stride/app:dev: ./src/contexts/chain.tsx
```

**Comment by assafmo** [comment]
can you tell me what repo, commit, package manager & node version you're using?

**Comment by srph** [comment]
@assafmo Oh, we're using pnpm on the Stride Frontend (pnpm v7.33.5, node v18.13.0). From what I understand about ESM (I did more digging last week), we probably should not being using an exported file (what we're doing in https://github.com/Stride-Labs/stridejs/pull/15) so we can allow for treeshaking where possible.

I can look into this.

**Comment by srph** [comment]
Fixed it - looks like we just needed to get rid of dependencies being included in the build (with esbuild-node-externals).

We've spent a bit more on this than expected, so I'm deferring optimizing our build further. We currently have a 4mb bundle, but but this should get fixed up down the line by apps that have their own build systems.

**Comment by assafmo** [comment]
AMAZING WORK!!

**Comment by assafmo** [comment]
I'm now thinking we should also add cosmwasm protobufs in here, but not super urgent unless you need it in the ui

**Pull request merged**
